const { db } = require('../config/firebase');
const redisClient = require('../config/redis');

// Get all manga (example of Cache-first)
const getMangaList = async (req, res) => {
    try {
        const mangaRef = db.collection('mangas');
        const snapshot = await mangaRef.get();
        
        if (snapshot.empty) {
            return res.status(200).json({ data: [] });
        }

        const mangas = [];
        snapshot.forEach(doc => {
            mangas.push({ id: doc.id, ...doc.data() });
        });

        // Set to Redis if cacheKey was generated by cacheMiddleware
        if (res.locals.cacheKey) {
            // Cache for 1 hour (3600 seconds)
            await redisClient.set(res.locals.cacheKey, JSON.stringify(mangas), 'EX', 3600);
        }

        res.status(200).json({
            fromCache: false,
            data: mangas
        });
    } catch (error) {
        console.error('Error fetching manga list:', error);
        res.status(500).json({ error: 'Internal server error' });
    }
};

module.exports = {
    getMangaList
};
